name       : openimagedenoise
version    : 1.4.1
release    : 6
source     :
    - https://github.com/OpenImageDenoise/oidn/releases/download/v1.4.1/oidn-1.4.1.src.tar.gz : 9088966685a78adf24b8de075d66e4c0019bd7b2b9d29c6e45aaf35d294e3f6f
license    : Apache-2.0
homepage   : https://www.openimagedenoise.org/
component  : multimedia.library
summary    : High-Performance Denoising Library for Ray Tracing
description: |
    The purpose of Intel Open Image Denoise is to provide an open, high-quality, efficient, and easy-to-use denoising library that allows one to significantly reduce rendering times in ray tracing based rendering applications.
clang      : yes
avx2       : yes
optimize   :
    - icf-all
    - thin-lto
builddeps  :
    - intel-tbb-devel
    - ispc
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
