name       : openimagedenoise
version    : 1.2.4
release    : 4
source     :
    - https://github.com/OpenImageDenoise/oidn/releases/download/v1.2.4/oidn-1.2.4.src.tar.gz : 948b070c780b5de0d983e7d5d37f6d9454932cc278913d9ee5b0bd047d23864a
license    : Apache-2.0
component  : multimedia.library
summary    : High-Performance Denoising Library for Ray Tracing
description: |
    The purpose of Intel Open Image Denoise is to provide an open, high-quality, efficient, and easy-to-use denoising library that allows one to significantly reduce rendering times in ray tracing based rendering applications.
builddeps  :
    - intel-tbb-devel
    - ispc
clang      : yes
avx2       : yes
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
