name       : openimagedenoise
version    : 1.4.2
release    : 8
source     :
    - https://github.com/OpenImageDenoise/oidn/releases/download/v1.4.2/oidn-1.4.2.src.tar.gz : e70d27ce24b41364782376c1b3b4f074f77310ccfe5f8ffec4a13a347e48a0ea
license    : Apache-2.0
homepage   : https://www.openimagedenoise.org/
component  : multimedia.library
summary    : High-Performance Denoising Library for Ray Tracing
description: |
    The purpose of Intel Open Image Denoise is to provide an open, high-quality, efficient, and easy-to-use denoising library that allows one to significantly reduce rendering times in ray tracing based rendering applications.
clang      : yes
avx2       : yes
optimize   :
    - icf-all
    - thin-lto
builddeps  :
    - pkgconfig(OpenImageIO)
    - intel-tbb-devel
    - ispc
setup      : |
    %cmake_ninja -DOIDN_APPS_OPENIMAGEIO=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -f $installdir/usr/bin/oidnTest
check      : |
    if [[ -z "${AVX2BUILD}" ]]; then
        ./solusBuildDir/oidnTest
    fi
